barcodebucket_newsagent_scraper:
    pattern: /scraper/{fullBarcode}
    defaults: { _controller: barcodebucket_newsagent.controller.webinforiv:barcodeAction }
    requirements: { gtin: '[0-9]{18}' }
    options: { i18n: false }
